### ISSUE TITLE
Error 😔

### ISSUE THREAD

**Issue by smir-ant** [a6b8/markdown-titles-to-svg-for-ruby#1]
ERROR:  Could not find a valid gem 'markdown_headlines_to_svg' (>= 0) in any repository
ERROR:  Possible alternatives: markdown_titles_to_svg, markdown-helpers, markdown-tables, markdown_extension, markdown_handler, markdown_helper, markdown_videos

I got this in my terminal. I'm not ruby developer and i don't know this language. But i want to use it. Help, please.

**Comment by a6b8** [comment]
Hello Smir-Ant,

I apologize for the late response.

As I understand it, you have to install the gem locally on your computer first. Use this command:

```gem install markdown_titles_to_svg``` (latest version is 0.2)

Then it should work. Here's a snippet to output the word "headline" as a .svg:

```ruby
require 'markdown_titles_to_svg'

svg = MarkdownTitlesToSvg.single( 
    'headline',
    :h1,
    {}
)

File.open( 'headline-123456.svg', 'w' ) { | f | f.write( svg ) }
```

Best regards
